version: '2'
services:
  db_ping:
    build:
      context: .
      dockerfile: Dockerfile.dbPing
    volumes:
    - /var/dbPing:/var/dbPing

  quick_plot:
    build:
      context: .
      dockerfile: Dockerfile.quickPlot
    volumes:
    - /var/dbPing:/var/dbPing
