FROM python:alpine
RUN pip install pew
RUN git clone https://github.com/dentearl/quick_plot /code
WORKDIR /code
COPY quickPlotRequirements.txt /code/requirements.txt
RUN pew new QUICK_PLOT -r requirements.txt
RUN make
CMD bash entry.quickPlot.sh


